### ISSUE TITLE
Difference in the shinyproxi doc and the README of this repo

### ISSUE THREAD

**Issue by DimitriF** [openanalytics/shinyproxy-shiny-demo-minimal#1]
Hi,
There is a difference for the command to build the image  between this page: http://www.shinyproxy.io/deploying-apps/ and the README of this repo.
In the doc:
`sudo docker build openanalytics/shinyproxy-template .`

In this repo:
`sudo docker build -t openanalytics/shinyproxy-template .`

The first one return an error:
`"docker build" requires exactly 1 argument(s).`

Apart from this, the doc is clear
thanks

**Comment by tverbeke** [comment]
Thanks! Fixed now.
