### ISSUE TITLE
what makes `getOption("shiny.host")` return 0.0.0.0

### ISSUE THREAD

**Issue by romunov** [openanalytics/shinyproxy-shiny-demo-minimal#4]
When running the application ([as in the demo](https://github.com/openanalytics/shinyproxy-template/blob/master/Dockerfile#L35)) some setups return `NULL` while others return `0.0.0.0` when queried with `getOption("shiny.host")`. I was unable to find how shiny sets this value but I suspect it depends on more than just R or R packages (maybe some javascript dependency?). When I try this in various docker containers I get mixed results (some return NULL while others return 0.0.0.0). Does anyone have any more information on how what influences what the function returns?

As a result, I've started to name host and port parameters explicitly (`shiny::runApp('/root/euler', host = "0.0.0.0", port = 3838)`.

**Comment by mnazarov** [comment]
A call to `getOption("shiny.host")` checks whether a global R option "shiny.host" was set. The `shiny` package itself doesn't set this option (but uses it if set), and the option doesn't depend on anything except R.
In the linked demo the option is set inside the [`Rprofile.site` file](https://github.com/openanalytics/shinyproxy-template/blob/master/Rprofile.site), which gets loaded by R on startup. This allows to omit the arguments in the `runApp` call. One possibility why this file may not be loading is when it is put in a wrong location (see https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html on when and where R looks for it)

**Comment by romunov** [comment]
Looks like my copying of Rprofile.site was wrong, should have been `/usr/local/lib/R/etc` (for rocker/r-ver:3.6.2 image).

**Comment by mnazarov** [comment]
> Looks like my copying of Rprofile.site was wrong, should have been `/usr/local/lib/R/etc` (for rocker/r-ver:3.6.2 image).

Yes, afaik this differs if R is installed from binary (r-base case) or from source (r-ver case)
