### ISSUE TITLE
Build failure due to expired GPG key

### ISSUE THREAD

**Issue by eturkes** [openanalytics/shinyproxy-shiny-demo-minimal#6]
Hi,

The GPG key for `https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/` needs to be updated. Adding the following line before the `apt-get` calls fixes it:

```
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```

I see that you have a similar line in the `openanalytics/r-base` base image with the old GPG key. It's probably best that it's updated over there.

**Comment by LEDfan** [comment]
Hi, thank you for opening this issue. In the meantime this should have been fixed, therefore I'm going to close this issue.
